<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>QuestFOV</AssemblyName>
    <RootNamespace>QuestFOV</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BoneLib">
      <HintPath>lib/BoneLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>lib/MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
